### ISSUE TITLE
BIG-IP Declaration fails when DHCP is available

### ISSUE THREAD

**Issue by gdmoore85** [F5Networks/f5-declarative-onboarding#129]
### Environment
 * Declarative Onboarding Version: 1.10.0
 * BIG-IP Version: **15.1.0.1, 14.1.2.3**
 * VMware 6.7 U3

### Summary
Declarative Onboarding declaration fails when DHCP is available for the management interface.  Even though the management interface is set to a static IP address seems as though the DHCP service is still present.  One thing to note, the BIG-IP is manually being licensed due to the license type that I am using.  Not sure it makes a difference but worth noting(which is why there is no licensing in the declaration.

**Received the same behavior on 15.1.0.1 as well as 14.1.2.3**

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "DO",
	"targetHost": "bip01.compute.internal",
	"targetUsername": "admin",
	"targetPassphrase": "*********",
	"declaration": {
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json",
        "schemaVersion": "1.9.0",
        "class": "Device",
        "async": true,
        "label": "BIP01 declarative onboarding declaration",
        "Common": {
            "class": "Tenant",
            "hostname": "bip01.compute.internal",
            "myDns": {
                "class": "DNS",
                "nameServers": [
		    "10.16.10.254",
                    "8.8.8.8"
                ],
                "search": [
                    "us-west-2-compute.internal",
                    "f5.com"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "2.pool.ntp.org",
		    "0.pool.ntp.org"
                ],
                "timezone": "America/Chicago"
            },
            "myProvisioning": {
                "class": "Provision",
                "ltm": "nominal",
                "gtm": "minimum",
                "apm": "nominal",
                "asm": "nominal",
                "afm": "nominal"
            },
            "internal_vlan_10": {
                "class": "VLAN",
                "tag": 4094,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": false
                    }
                ],
                "cmpHash": "dst-ip"
            },
            "external_vlan_20": {
                "class": "VLAN",
                "tag": 4093,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": false
                    }
                ],
                "cmpHash": "dst-ip"
            },
            "ha_vlan_10": {
                "class": "VLAN",
                "tag": 4092,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.3",
                        "tagged": false
                    }
                ],
                "cmpHash": "dst-ip"
            },
            "internal_self": {
                "class": "SelfIp",
                "address": "10.16.10.22/24",
                "vlan": "internal_vlan_10",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            },
            "internal_floating": {
                "class": "SelfIp",
                "address": "10.16.10.23/24",
                "vlan": "internal_vlan_10",
                "allowService": "default",
                "trafficGroup": "traffic-group-1"
            },
            "external_self": {
                "class": "SelfIp",
                "address": "10.16.20.22/24",
                "vlan": "external_vlan_20",
                "allowService": "none",
                "trafficGroup": "traffic-group-local-only"
            },
            "external_floating": {
                "class": "SelfIp",
                "address": "10.16.20.23/24",
                "vlan": "external_vlan_20",
                "allowService": "none",
                "trafficGroup": "traffic-group-1"
            },
            "default": {
                "class": "Route",
                "gw": "10.16.10.1",
                "network": "default",
                "mtu": 1500
            },
            "configsync": {
                "class": "ConfigSync",
                "configsyncIp": "/Common/internal_self/address"
            },
            "failoverAddress": {
                "class": "FailoverUnicast",
                "address": "/Common/internal_self/address"
            },
            "failoverGroup": {
                "class": "DeviceGroup",
                "type": "sync-failover",
                "members": [
                    "bip01.compute.internal",
                    "bip02.compute.internal"
                ],
                "owner": "/Common/failoverGroup/members/0",
                "autoSync": true,
                "saveOnAutoSync": true,
                "networkFailover": true,
                "fullLoadOnSync": false,
                "asmSync": true
            },
            "trust": {
                "class": "DeviceTrust",
                "localUsername": "admin",
                "localPassword": "*********",
                "remoteHost": "/Common/failoverGroup/members/0",
                "remoteUsername": "admin",
                "remotePassword": "*********"
            }
        }
    }
}
```
The above declaration has been sent using both the DO container as well as directly to the BIG-IP with DO installed.  After the initial failure I can resend the same declaration several times and it will work after the third or fourth attempt.

### Expected Behavior
```json
{
    "id": "3dd0b663-b62d-413e-9aea-702d3c9c05c3",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/3dd0b663-b62d-413e-9aea-702d3c9c05c3",
    "result": {
        "class": "Result",
        "code": 200,
        "status": "OK",
        "message": "success"
    },
```
### Actual Behavior
```json 
{
        "class": "Result",
        "code": 500,
        "status": "ERROR",
        "message": "invalid config - rolled back",
        "errors": [
            "tryUntil: max tries reached: dhclient status is * dhclient.service - dhclient automatically configures the management interface when DHCP is available.\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; enabled; vendor preset: enabled)\n   Active: active (exited) since Tue 2020-03-10 08:02:34 PDT; 1min 4s ago\n  Process: 29660 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=0/SUCCESS)\n  Process: 29782 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\n\nMar 10 08:02:34 localhost.localdomain systemd[1]: Starting dhclient automatically configures the management interface when DHCP is available....\nMar 10 08:02:34 localhost.localdomain dhclient[29782]: Current management-ip configuration mode for IPV4 is: Static.\nMar 10 08:02:34 localhost.localdomain systemd[1]: Started dhclient automatically configures the management interface when DHCP is available..\n",
            "tryUntil: max tries reached: dhclient status is * dhclient.service - dhclient automatically configures the management interface when DHCP is available.\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; enabled; vendor preset: enabled)\n   Active: active (exited) since Tue 2020-03-10 08:02:34 PDT; 1min 4s ago\n  Process: 29660 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=0/SUCCESS)\n  Process: 29782 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\n\nMar 10 08:02:34 localhost.localdomain systemd[1]: Starting dhclient automatically configures the management interface when DHCP is available....\nMar 10 08:02:34 localhost.localdomain dhclient[29782]: Current management-ip configuration mode for IPV4 is: Static.\nMar 10 08:02:34 localhost.localdomain systemd[1]: Started dhclient automatically configures the management interface when DHCP is available..\n"
        ]
}
```

**Comment by JeffGiroux** [comment]
I run into this same issue. I'm running latest image in Azure with 2 BIG-IP instances. All latest terraform provider updates and all latest F5 A&O RPM versions. When I run DO, I get the same error code 500 due to dhcp conflicts. If I run the DO declaration again (or maybe 1-2 more), then it finally kicks in and the HA pair forms.

Also, seems possible duplicate to https://github.com/F5Networks/f5-declarative-onboarding/issues/43

**Comment by dstokesf5** [comment]
Thank you for reporting this, we have added it to our internal product backlog as  AUTOTOOL-1387.

**Comment by alonsocamaro** [comment]
Could you please indicate a workaround?

**Comment by alonsocamaro** [comment]
Added qkviews from customer where I see what partner is reporting:
- no issue with v14
- issue with v15
A colleague is not experiencing this problem with either when using DHCP. Always using the same  declaration.

See qkview links next:

https://ihealth.f5.com/qkview-analyzer/qv/13286593/status/overview
https://ihealth.f5.com/qkview-analyzer/qv/13426374/status/overview

**Comment by JeffGiroux** [comment]
Disabling dhcp during onboarding (aka Azure extensions, user-data, cloud-init, etc) will allow a successful DO declaration. I just tested various clusters with various settings like disabling gui setup, walking through gui setup and changing mgmt IP, and more. After all testing, my DO goes through in Azure if I disable DHCP.

Workaround...
modify sys global-settings mgmt-dhcp disabled
save sys config

Not the best workaround if someone needs dhcp later. I guess when DO pushes the declaration you can then automate the enabling of dhcp again

So...
1. spin up BIG-IP
2. run various tmsh commands in onboard script
3. same onboard script downloads DO RPMs and installs
4. Orchestration tool (or onboard script) then POSTs DO declaration
5. Upon success, tmsh command or API call is run to set mgmt-dhcp = enabled

**Comment by JeffGiroux** [comment]
I validated this is fixed with 1.13. Should this be marked closed?

**Comment by dstokesf5** [comment]
Thanks for confirming this is fixed. We cleaned up some stuff related to DHCP that likely affected a few issues. Closing.

**Comment by leondelyon3** [comment]
Hi,
still get the same issue on ve (4 nic) running v14.1.2.6 either with DO v1.14 or v1.13.0-5.
See below the DO result with v1.13, I've just erased the license reg key used: 
{
    "id": "fe7cdafe-dbc8-4593-bf91-93fb20df0e7e",
    "selfLink": "https://localhost/mgmt/shared/declarative-onboarding/task/fe7cdafe-dbc8-4593-bf91-93fb20df0e7e",
    "result": {
        "class": "Result",
        "code": 202,
        "status": "ROLLING_BACK",
        "message": "invalid config - rolling back",
        "errors": [
            "tryUntil: max tries reached: dhclient status is * dhclient.service - SYSV: dhclient automatically configures the management interface when DHCP is available.\n   Loaded: loaded (/etc/rc.d/init.d/dhclient; bad; vendor preset: disabled)\n   Active: active (exited) since Sun 2020-08-09 05:15:25 PDT; 1min 2s ago\n     Docs: man:systemd-sysv-generator(8)\n  Process: 17998 ExecStop=/etc/rc.d/init.d/dhclient stop (code=exited, status=7)\n  Process: 18035 ExecStart=/etc/rc.d/init.d/dhclient start (code=exited, status=0/SUCCESS)\n\nAug 09 05:15:25 localhost.localdomain systemd[1]: Starting SYSV: dhclient automatically configures the management interface when DHCP is available....\nAug 09 05:15:25 localhost.localdomain dhclient[18035]: Current management-ip configuration mode for IPV4 is: Static.\nAug 09 05:15:25 localhost.localdomain systemd[1]: Started SYSV: dhclient automatically configures the management interface when DHCP is available..\n"
        ]
    },
    "declaration": {
        "$schema": "https://raw.githubusercontent.com/F5Networks/f5-declarative-onboarding/master/src/schema/latest/base.schema.json",
        "schemaVersion": "1.13.0",
        "class": "Device",
        "async": true,
        "label": "my BIG-IP declaration for declarative onboarding",
        "Common": {
            "class": "Tenant",
            "hostname": "BigIP-DO-B-Student3.lab",
            "myLicense": {
                "class": "License",
                "licenseType": "regKey",
                "regKey": "bla-bla",
                "overwrite": false
            },
            "deviceCertificate": {
                "class": "DeviceCertificate",
                "certificate": {
                    "base64": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVIVENDQXdXZ0F3SUJBZ0lVQXpYTFliaHgxNHg5dElXNCtnbnk3ZmROcGlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZc3hDekFKQmdOVkJBWVRBa1pTTVE0d0RBWURWUVFJREFWU2FHOXVaVEVOTUFzR0ExVUVCd3dFVEhsdgpiakVMTUFrR0ExVUVDZ3dDUmpVeEN6QUpCZ05WQkFzTUFsQlRNU0F3SGdZRFZRUUREQmRDYVdkSlVDMUVUeTFCCkxWTjBkV1JsYm5RekxteGhZakVoTUI4R0NTcUdTSWIzRFFFSkFSWVNiQzVqYUdGeWNHVnVZWGxBWmpVdVkyOXQKTUI0WERUSXdNRGd3TmpFeE5UazBNbG9YRFRNd01EZ3dOREV4TlRrME1sb3dnWXN4Q3pBSkJnTlZCQVlUQWtaUwpNUTR3REFZRFZRUUlEQVZTYUc5dVpURU5NQXNHQTFVRUJ3d0VUSGx2YmpFTE1Ba0dBMVVFQ2d3Q1JqVXhDekFKCkJnTlZCQXNNQWxCVE1TQXdIZ1lEVlFRRERCZENhV2RKVUMxRVR5MUJMVk4wZFdSbGJuUXpMbXhoWWpFaE1COEcKQ1NxR1NJYjNEUUVKQVJZU2JDNWphR0Z5Y0dWdVlYbEFaalV1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXJIL25EN1VNczI4Zkg4MWNJYUhhZS9Bc3VpTzhvcDMrTGlvZnB5cEtwVWVICmJCcDF4YSt6L1VmODJ6SzNBOWxxRlY4QWdza0diVXcwcno3SDFLODRhd1g3VDlkUFdtYWQrK05IQ01NMHJHQ2cKZmJVeUxtUkFQMGo5WXE3TVFyQ1ltTXd5aitJZ1dJTksyZEJUYUN3NmtLc0xzSFd2SGswanBGRThmOGVkaTA3dApCRDlrbUVHQ2tVS2VnNlVrS1l1VFA4d1N0TGc3M0IreEtnczFqemd4NkI2RmRlNHpHQ1RvV2puc1YrZ2FEOHplCkh3K1hyUkdpRVJpQVo2WWIwQk9iUEdGWXNTQ2RueUFMenJSdzFVQ1Z4WVhLaXRSc3ppM3NuZ2NXemx5MDlqa2oKZ2hxNVVtYTBrdGxuTVEyaFJuazMrbVR1b2EzOTBicU1RRkw4S1o5enpRSURBUUFCbzNjd2RUQWRCZ05WSFE0RQpGZ1FVak1wYlNBNkxMZk5mU3o3K0xiU0VNY0NqK0F3d0h3WURWUjBqQkJnd0ZvQVVqTXBiU0E2TExmTmZTejcrCkxiU0VNY0NqK0F3d0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBaUJnTlZIUkVFR3pBWmdoZENhV2RKVUMxRVR5MUIKTFZOMGRXUmxiblF6TG14aFlqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFORDRxM0ZtMjVMbmlJQW55dUNEegppQWhKSXozTzQ3TnI1WGpsL21ISzhNaitIN09DMURGZi9ncjdkWGw0NmlQNk9JaEtMM3Y2N0lKREk2L01qRlJRCmZYb25EVEtEYXM4THVIN3VWaFBROEVzSjlCeUtjRUkyMGFzM212SzVmSitZQ09zZDRpaUYzQzNsbkRaWWVYb3IKejcvTHdZSTFpL3I4cWhwTW83MWt0SUx0QmZSMXNlVDdZb3pwaGRibDFtSjB0Tzd2T3FGb2p5WENDdWZWNjRwRgpjUjNBaTE2cld2ckYvSHU4Q2hmRmRHT2k3SkZoQjB3MThOZFd2K25Nc2haWTRSWkIzRkR4MHJqaW1rUTB1OSt2Clk5aHdvZ0RiUUZOWUVzVkc0UjBWeE5ERTFIV2czN2lvR2l3dFZyZXpYTHVFUU82b2NscGxqcExSYmh1KytHUEEKbHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
                }
            },
            "myDns": {
                "class": "DNS",
                "nameServers": [
                    "10.154.1.241",
                    "10.154.1.242",
                    "10.154.1.243",
                    "8.8.8.8"
                ]
            },
            "myNtp": {
                "class": "NTP",
                "servers": [
                    "pool.ntp.org"
                ],
                "timezone": "Europe/Paris"
            },
            "myProvisioning": {
                "class": "Provision",
                "ltm": "nominal",
                "afm": "nominal",
                "pem": "nominal",
                "apm": "nominal"
            },
            "internal": {
                "class": "VLAN",
                "tag": 4093,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.2",
                        "tagged": false
                    }
                ],
                "cmpHash": "dst-ip"
            },
            "internal-self": {
                "class": "SelfIp",
                "address": "172.16.4.32/24",
                "vlan": "internal",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            },
            "external": {
                "class": "VLAN",
                "tag": 4094,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.1",
                        "tagged": false
                    }
                ],
                "cmpHash": "src-ip"
            },
            "external-self": {
                "class": "SelfIp",
                "address": "10.10.4.32/24",
                "vlan": "external",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            },
            "HA": {
                "class": "VLAN",
                "tag": 4092,
                "mtu": 1500,
                "interfaces": [
                    {
                        "name": "1.3",
                        "tagged": false
                    }
                ],
                "cmpHash": "default"
            },
            "HA-self": {
                "class": "SelfIp",
                "address": "192.168.1.6/24",
                "vlan": "HA",
                "allowService": "default",
                "trafficGroup": "traffic-group-local-only"
            }
        }
    }
}

Same result with v1.14

BR
Lionel
